// Centralized image-fallback system for Suplymate.
//
// Goal: NO supplier or product card is ever empty or broken. Every card always
// resolves to a real, non-broken image via this chain:
//
//   real DB image  →  scraped/imported image  →  category-based fallback  →
//   generic Suplymate placeholder
//
// IMAGE SOURCE CHOICE
// -------------------
// The category + generic fallbacks are LOCAL, branded SVG assets under
// `public/images/` (generated by `scripts/generate-fallback-images.cjs`).
// We deliberately avoid hotlinking fragile/random endpoints (e.g. the
// deprecated `source.unsplash.com`): local SVGs are zero-dependency,
// build-safe, never 404, render instantly, and look intentional (gradient +
// industrial glyph + category label + wordmark).
//
// Card photos prefer committed local stills under `/images/suppliers/…` and
// `/images/products/…`. Google Maps / googleusercontent URLs 403 and make
// `/_next/image` 502 on prod — they are never treated as usable card photos.
// Other remotes (Vercel Blob, mill sites) are used only when no local still
// exists. Swap in preferred photos any time by replacing the SVGs or pointing
// these maps at curated CDN URLs.

export type FallbackCategoryKey =
  | "steel"
  | "aluminum"
  | "cement"
  | "construction"
  | "packaging"
  | "electrical"
  | "machinery"
  | "industrial"
  | "textiles"
  | "office"
  | "pipes"
  | "hydraulic"
  | "chemicals"
  | "agriculture"
  | "default";

const PRODUCT_BASE = "/images/products";
const SUPPLIER_BASE = "/images/suppliers";

export const GENERIC_PRODUCT_PLACEHOLDER = "/images/placeholder-product.svg";
export const GENERIC_SUPPLIER_PLACEHOLDER = "/images/placeholder-supplier.svg";

// Keyword → category. Ordered by specificity (most specific first) so e.g.
// "stainless steel pipe" maps to pipes only if "pipe" wins; we check the more
// specific industrial terms before generic metal terms.
const KEYWORD_MAP: { match: RegExp; key: FallbackCategoryKey }[] = [
  { match: /hydraulic|cylinder|pneumatic/i, key: "hydraulic" },
  { match: /pipe|tube|tubing|duct|fitting/i, key: "pipes" },
  { match: /cable|wire|electric|electronic|circuit|pcb|connector|cabl/i, key: "electrical" },
  { match: /packag|carton|box|crate|pallet|film|wrap/i, key: "packaging" },
  { match: /textile|fabric|yarn|cloth|woven|apparel/i, key: "textiles" },
  { match: /office|stationery|paper|furniture/i, key: "office" },
  { match: /chemical|polymer|resin|solvent|coating/i, key: "chemicals" },
  { match: /agri|food|grain|farm|crop|agro/i, key: "agriculture" },
  { match: /cement|concrete|aggregate|mortar/i, key: "cement" },
  { match: /aluminum|aluminium|alloy coil/i, key: "aluminum" },
  { match: /machine|machinery|gear|bearing|cnc|equipment|motor|pump/i, key: "machinery" },
  { match: /construction|building|btp|insulation|roofing|brick/i, key: "construction" },
  { match: /steel|metal|iron|rebar|beam|coil|plate|sheet/i, key: "steel" },
  { match: /industrial|part|component|mro/i, key: "industrial" },
];

// Explicit mapping for the canonical ProductCategory enum values.
const PRODUCT_CATEGORY_MAP: Record<string, FallbackCategoryKey> = {
  "steel & metals": "steel",
  "cables & electrical": "electrical",
  "tubes & pipes": "pipes",
  packaging: "packaging",
  construction: "construction",
  "industrial parts": "industrial",
};

// Explicit mapping for the supplier Industry / SupplierCategory enums.
const SUPPLIER_CATEGORY_MAP: Record<string, FallbackCategoryKey> = {
  metal: "steel",
  "steel & metals": "steel",
  "construction & btp": "construction",
  construction: "construction",
  "industrial equipment": "machinery",
  "industrial parts": "industrial",
  "electrotechnical & cabling": "electrical",
  "cables & electrical": "electrical",
  "tubes & pipes": "pipes",
  "plastics & packaging": "packaging",
  packaging: "packaging",
  "agriculture & agrofood": "agriculture",
};

function classify(
  text: string | undefined | null,
  explicit?: Record<string, FallbackCategoryKey>
): FallbackCategoryKey {
  const raw = (text ?? "").trim().toLowerCase();
  if (!raw) return "default";
  if (explicit && explicit[raw]) return explicit[raw];
  for (const { match, key } of KEYWORD_MAP) {
    if (match.test(raw)) return key;
  }
  return "default";
}

/**
 * Category-based fallback image for a product. Resolves from the (optional)
 * category first, then the product name, so even free-text scraped products
 * get a relevant tile. Always returns a local, never-broken SVG path.
 */
export function getProductFallbackImage(
  productName?: string,
  category?: string
): string {
  let key = classify(category, PRODUCT_CATEGORY_MAP);
  if (key === "default") key = classify(productName);
  return `${PRODUCT_BASE}/${key}.svg`;
}

/**
 * Google Maps / Places / Street View photo hosts. These URLs 403 for anonymous
 * `/_next/image` fetches and must never be passed to next/image on cards.
 */
export function isGoogleMapsImageUrl(url?: string | null): boolean {
  if (typeof url !== "string") return false;
  const value = url.trim();
  if (!/^https?:\/\//i.test(value)) return false;
  try {
    const host = new URL(value).hostname.toLowerCase();
    return (
      host === "googleusercontent.com" ||
      host.endsWith(".googleusercontent.com") ||
      host === "streetviewpixels-pa.googleapis.com" ||
      host.endsWith(".ggpht.com") ||
      host === "maps.gstatic.com" ||
      host === "maps.googleapis.com"
    );
  } catch {
    return /googleusercontent\.com|streetviewpixels-pa\.googleapis\.com|maps\.gstatic\.com|maps\.googleapis\.com|\.ggpht\.com/i.test(
      value,
    );
  }
}

/** Curated mill/product stills checked into `public/images/{suppliers,products}/`. */
export function isLocalStillUrl(url?: string | null): boolean {
  if (typeof url !== "string") return false;
  return /^\/images\/(suppliers|products)\/.+\.(jpe?g|png|webp)$/i.test(url.trim());
}

/**
 * True only for a REAL photograph we can render on a card: a local raster
 * still, or a non-Maps remote http(s) photo. Google Maps / googleusercontent
 * URLs, local branded SVG tiles, and empty values are NOT real photos.
 */
export function isRealImageUrl(url?: string | null): boolean {
  if (typeof url !== "string") return false;
  const value = url.trim();
  if (isGoogleMapsImageUrl(value)) return false;
  if (/^https?:\/\//i.test(value)) return true;
  return /^\/images\/.+\.(jpe?g|png|webp)$/i.test(value);
}

/**
 * Prefer a local mill/product still; otherwise the first non-Maps real photo.
 * Returns undefined when only Maps URLs / empty values are present.
 */
export function pickPreferredCardImage(
  urls?: (string | null | undefined)[] | null,
): string | undefined {
  const list = (urls ?? [])
    .filter((u): u is string => typeof u === "string" && Boolean(u.trim()))
    .map((u) => u.trim());
  const local = list.find((u) => isLocalStillUrl(u));
  if (local) return local;
  return list.find((u) => isRealImageUrl(u));
}

export function supplierHasUsableCardImage(s: {
  imageUrl?: string | null;
  supplierImages?: (string | null | undefined)[] | null;
}): boolean {
  return Boolean(pickPreferredCardImage([s.imageUrl, ...(s.supplierImages ?? [])]));
}

export type ProductImageInput = {
  /** Real images attached to the product itself (DB / scraped). */
  images?: (string | null | undefined)[] | null;
  /**
   * Real photos inherited from the linked supplier (e.g. Google Maps / website
   * media). Used as a secondary real-photo source for product cards.
   */
  supplierImages?: (string | null | undefined)[] | null;
  productName?: string;
  category?: string;
};

/**
 * Return the first REAL product photo if one exists, walking:
 *   product image → linked-supplier photo → (undefined).
 * Returns undefined when only category fallbacks would be available, so callers
 * can distinguish "has a real photo" from "needs a generated tile".
 */
export function getRealProductImage(input: ProductImageInput): string | undefined {
  return pickPreferredCardImage([
    ...(input.images ?? []),
    ...(input.supplierImages ?? []),
  ]);
}

/**
 * Whether a product can be shown with a genuine photograph (its own or its
 * linked supplier's). Drives the homepage real-photo-only rule and ranks
 * photo-bearing products above fallback-only ones in the catalogue.
 */
export function hasRealProductImage(input: ProductImageInput): boolean {
  return Boolean(getRealProductImage(input));
}

/**
 * Best image for a product, guaranteed never broken/empty. Priority:
 *   real product photo → linked-supplier photo → category fallback → placeholder.
 * Always returns a renderable URL (the category fallback is a local SVG).
 */
export function getBestProductImage(input: ProductImageInput): string {
  return (
    getRealProductImage(input) ??
    getProductFallbackImage(input.productName, input.category) ??
    GENERIC_PRODUCT_PLACEHOLDER
  );
}

/**
 * Category-based cover/business photo fallback for a supplier. Resolves from
 * the industry/category first, then the supplier name. Always returns a local,
 * never-broken SVG path.
 */
export function getSupplierFallbackImage(
  industry?: string,
  supplierName?: string
): string {
  let key = classify(industry, SUPPLIER_CATEGORY_MAP);
  if (key === "default") key = classify(supplierName);
  return `${SUPPLIER_BASE}/${key}.svg`;
}

export type SupplierLogoFallback = {
  /** 1–2 letter initials derived from the supplier name. */
  initials: string;
  /** Inline CSS gradient (use via style={{ backgroundImage }}). */
  gradient: string;
};

const LOGO_GRADIENTS = [
  "linear-gradient(135deg, #0ea5b7, #14b8a6)",
  "linear-gradient(135deg, #1e3a5f, #0ea5b7)",
  "linear-gradient(135deg, #14b8a6, #10b981)",
  "linear-gradient(135deg, #0284c7, #14b8a6)",
  "linear-gradient(135deg, #0D3349, #0284c7)",
  "linear-gradient(135deg, #10b981, #0ea5b7)",
];

function hashString(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function deriveInitials(name: string): string {
  const words = (name ?? "")
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (words.length === 0) return "S";
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[1][0]).toUpperCase();
}

/**
 * Initials-based logo fallback (data for an initials avatar — NOT an image
 * URL). Deterministic gradient so the same supplier always looks identical.
 */
export function getSupplierLogoFallback(supplierName: string): SupplierLogoFallback {
  const seed = hashString(supplierName || "Suplymate");
  return {
    initials: deriveInitials(supplierName),
    gradient: LOGO_GRADIENTS[seed % LOGO_GRADIENTS.length],
  };
}
