"use client";

import { motion } from "framer-motion";
import {
  Brain,
  Sparkles,
  TrendingUp,
  ShieldAlert,
  Target,
  Globe2,
  Handshake,
} from "lucide-react";
import type { SupplierProfile } from "@/lib/supplier-profile";
import { Sparkline } from "./primitives";

const TONE: Record<string, string> = {
  positive: "text-emerald-400",
  neutral: "text-cyan-glow",
  watch: "text-amber-400",
};

export default function AiInsightsSection({ profile }: { profile: SupplierProfile }) {
  const { ai, base } = profile;

  return (
    <section className="relative overflow-hidden bg-navy-dark py-14 text-white">
      <div className="absolute inset-0 ai-grid-bg opacity-[0.07]" />
      <div
        className="absolute -left-20 top-10 h-72 w-72 rounded-full opacity-30 blur-3xl"
        style={{ background: "radial-gradient(circle, rgba(212,175,55,0.4), transparent 70%)" }}
      />
      <div
        className="absolute -right-20 bottom-0 h-72 w-72 rounded-full opacity-30 blur-3xl"
        style={{ background: "radial-gradient(circle, rgba(96,165,250,0.4), transparent 70%)" }}
      />

      <div className="container-page relative">
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-8 flex items-start gap-3"
        >
          <span className="mt-0.5 flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-gold/30 to-ai-glow/20 text-gold-light">
            <Brain className="h-5 w-5" aria-hidden />
          </span>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-gold-light">
              Suplymate AI
            </p>
            <h2 className="text-xl font-bold tracking-tight sm:text-2xl">
              AI procurement intelligence
            </h2>
            <p className="mt-1 max-w-2xl text-sm text-white/60">
              Generated by Suplymate&apos;s sourcing model · {ai.overallConfidence}% overall confidence
            </p>
          </div>
        </motion.div>

        {/* Analysis + risk */}
        <div className="grid gap-4 lg:grid-cols-2">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur"
          >
            <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-gold-light">
              <Sparkles className="h-4 w-4" aria-hidden /> Supplier analysis
            </div>
            <p className="text-sm leading-relaxed text-white/75">{ai.analysis}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.08 }}
            className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur"
          >
            <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-amber-300">
              <ShieldAlert className="h-4 w-4" aria-hidden /> Risk analysis
            </div>
            <p className="text-sm leading-relaxed text-white/75">{ai.riskAnalysis}</p>
          </motion.div>
        </div>

        {/* Insight cards */}
        <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {ai.cards.map((c, i) => (
            <motion.div
              key={c.id}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.45, delay: i * 0.06 }}
              className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[0.07] to-white/[0.02] p-5 backdrop-blur transition hover:border-gold/30"
            >
              <div className="flex items-center justify-between">
                <span className={`text-xs font-semibold ${TONE[c.tone]}`}>{c.confidence}%</span>
                <span className="text-[10px] uppercase tracking-wider text-white/40">confidence</span>
              </div>
              <div className="my-3">
                <Sparkline data={c.trend} color="#E8C96A" className="h-10 w-full" />
              </div>
              <p className="text-sm font-bold text-white">{c.title}</p>
              <p className="mt-1 text-xs leading-relaxed text-white/55">{c.body}</p>
            </motion.div>
          ))}
        </div>

        {/* Recommendations + negotiation + markets */}
        <div className="mt-4 grid gap-4 lg:grid-cols-3">
          <RecoCard
            icon={Target}
            title="Sourcing recommendations"
            items={ai.sourcingRecommendations}
            accent="text-cyan-glow"
          />
          <RecoCard
            icon={Handshake}
            title="Negotiation insights"
            items={ai.negotiationInsights}
            accent="text-gold-light"
          />
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur"
          >
            <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-emerald-300">
              <Globe2 className="h-4 w-4" aria-hidden /> Best-fit markets
            </div>
            <div className="mb-4 flex flex-wrap gap-2">
              {ai.bestMarkets.map((m) => (
                <span key={m} className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-white/80">
                  {m}
                </span>
              ))}
            </div>
            <div className="space-y-2 text-xs text-white/60">
              <Stat label="Pricing competitiveness" value={`${ai.pricingCompetitiveness}%`} />
              <Stat label="Delivery reliability (forecast)" value={`${ai.deliveryReliabilityPrediction}%`} />
              <div className="flex items-center gap-2 pt-1">
                <TrendingUp className="h-3.5 w-3.5 text-emerald-300" aria-hidden />
                <span>Demand trend for {base.categoryLabel.toLowerCase()}</span>
                <span className="ml-auto w-20">
                  <Sparkline data={ai.demandTrend} color="#34D399" className="h-6 w-full" fill={false} />
                </span>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

function RecoCard({
  icon: Icon,
  title,
  items,
  accent,
}: {
  icon: typeof Target;
  title: string;
  items: string[];
  accent: string;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur"
    >
      <div className={`mb-3 flex items-center gap-2 text-sm font-semibold ${accent}`}>
        <Icon className="h-4 w-4" aria-hidden /> {title}
      </div>
      <ul className="space-y-2.5">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-xs leading-relaxed text-white/70">
            <span className={`mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-current ${accent}`} />
            {it}
          </li>
        ))}
      </ul>
    </motion.div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span>{label}</span>
      <span className="font-bold text-white">{value}</span>
    </div>
  );
}
